

name: .NET Core Desktop

on:
   watch:
    types: [started]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest  # For a list of available runner types, refer to 
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: CNSubtitles.sln
      # Replace with your solution name, i.e. MyWpfApp.sln.
      Test_Project_Path: \CnSub\CnSub.csproj                 # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.
      #Wap_Project_Directory: your-wap-project-directory-name    # Replace with the Wap project directory relative to the solution, i.e. MyWpfApp.Package.
      #Wap_Project_Path: your-wap-project-path                   # Replace with the path to your Wap project, i.e. MyWpf.App.Package\MyWpfApp.Package.wapproj.

jobs:
  ci_build:
    name: Build
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodule: 'true'
    - name: Checkout Submodules
      shell: bash
      run: |
        # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
        git config --global url."https://github.com/".insteadOf "git@github.com:"
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
    - name: Restore NuGet Package
      run: nuget restore CNSubtitles.sln
    - name: Prepare MSBuild
      uses: microsoft/setup-msbuild@v1.0.0
    - name: Build Project
      run: msbuild \CnSub\CnSub.csproj /p:Configuration=Release /verbosity:quiet
