

name: .NET Core Desktop

on:
   watch:
    types: [started]


jobs:
  ci_build:
    name: Build
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodule: 'true'
 
    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
    - name: Restore NuGet Package
      run: nuget restore CNSubtitles.sln
    - name: Prepare MSBuild
      uses: microsoft/setup-msbuild@v1.0.0
    - name: Build Project
      run: msbuild CnSub/CnSub.csproj /p:Configuration=Release /verbosity:quiet
    - name: Upload bin directory
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      with:
        name: subcn.dll
        path: dll/
